<?php

class ShiftService
{
    private ShiftSchedule $scheduleModel;

    public function __construct(PDO $db)
    {
        $this->scheduleModel = new ShiftSchedule($db);
    }

    /**
     * Generate jadwal shift otomatis untuk seorang user.
     *
     * Pola rotasi staff / team_leader (per flow.md):
     *   2 hari Pagi → 2 hari Siang → 2 hari Malam → 2 hari Libur → ulang
     *
     * Manager punya shift tetap (non-rotasi):
     *   hrd_manager       → shift id 4 (10:00-18:00, Senin-Jumat)
     *   technical_manager → shift id 5 (13:00-21:00, Senin-Jumat)
     *
     * @param int    $userId
     * @param string $role
     * @param string $startDate  Y-m-d
     * @param int    $days       jumlah hari ke depan yang di-generate
     */
    public function generateSchedule(int $userId, string $role, string $startDate, int $days = 30): void
    {
        $currentDate = new \DateTime($startDate);
        $pattern = [
            1, 1, // Pagi
            2, 2, // Siang
            3, 3, // Malam
            null, null // Libur
        ];

        for ($i = 0; $i < $days; $i++) {
            $dateStr = $currentDate->format('Y-m-d');
            $shiftId = null;
            $isDayOff = 0;

            if ($role === 'hrd_manager') {
                // Fixed Shift: Senin - Jumat (Shift 4), Sabtu - Minggu Libur
                $dayOfWeek = (int)$currentDate->format('N'); // 1 = Senin, 7 = Minggu
                if ($dayOfWeek <= 5) {
                    $shiftId = 4;
                } else {
                    $isDayOff = 1;
                }
            } elseif ($role === 'technical_manager') {
                // Fixed Shift: Senin - Jumat (Shift 5), Sabtu - Minggu Libur
                $dayOfWeek = (int)$currentDate->format('N');
                if ($dayOfWeek <= 5) {
                    $shiftId = 5;
                } else {
                    $isDayOff = 1;
                }
            } elseif ($role === 'c_level') {
                // c_level free bebas
                $isDayOff = 1;
            } else {
                // Staff / Team Leader (Rotasi 2-2-2-2)
                $loopIndex = $i % 8;
                $shiftId = $pattern[$loopIndex];
                if ($shiftId === null) {
                    $isDayOff = 1;
                }
            }

            $this->scheduleModel->create($userId, [
                'shift_id'   => $shiftId,
                'date'       => $dateStr,
                'is_day_off' => $isDayOff,
                'notes'      => 'Generated by system'
            ]);

            $currentDate->modify('+1 day');
        }
    }

    /**
     * Override jadwal shift manual (admin / HRD).
     */
    public function overrideSchedule(int $userId, string $date, ?int $shiftId, bool $isDayOff, string $notes = ''): bool
    {
        return $this->scheduleModel->create($userId, [
            'shift_id'   => $shiftId,
            'date'       => $date,
            'is_day_off' => $isDayOff ? 1 : 0,
            'notes'      => $notes
        ]);
    }

    /**
     * Ambil jadwal shift user untuk rentang tanggal tertentu.
     */
    public function getSchedule(int $userId, string $fromDate, string $toDate): array
    {
        return $this->scheduleModel->getByUserId($userId, [
            'start_date' => $fromDate,
            'end_date'   => $toDate
        ]);
    }

    /**
     * Ambil shift aktif user hari ini.
     * Return null jika hari libur atau tidak ada jadwal.
     */
    public function getTodaySchedule(int $userId): ?array
    {
        $schedules = $this->scheduleModel->getByUserId($userId, ['date' => date('Y-m-d')]);
        
        if (empty($schedules) || $schedules[0]['is_day_off']) {
            return null;
        }

        return $schedules[0];
    }
}
